# Generated by Django 4.1.7 on 2023-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(default='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
